# Tagoria Dailies Completer - Config

# Maintain the formatting given in this file

# Credentials
USERNAME: "username01"
PASSWORD: "password01"
WORLD: "1IN"
# Eg. International World 1

# Preferences
# Default location to plunder - options: Valley, River, Ruins, Mine, Canyon, Volcano
PLUNDER_LOCATION: "Canyon"
# Maximum amount of Amber to carry before spending on skillpoints
AMBER_MAX: 9001
